---
name: Forward one or more local ports of a service
command: kubectl port-forward svc/{{service_name}} {{local_port}}:{{service_port}}
tags:
  - kubernetes
description: "Listen on port specified locally, forwarding to the targetPort of the service's port with the same value in a pod selected by the service."
arguments:
  - name: service_name
    description: The specified service name
    default_value: ~
  - name: local_port
    description: localhost port number
    default_value: ~
  - name: service_port
    description: service port number
    default_value: ~
source_url: "https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#port-forward"
author: AI
author_url: "https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#port-forward"
shells: []
