name: Configures your NativeScript project for unit testing with a selected framework.
command: "ns test init {{framework}}"
tags:
  - nativescript
description: "Configures your NativeScript project for unit testing with a selected framework. This operation installs the @nativescript/unit-test-runner npm module and its dependencies and creates a tests folder in the app directory."
arguments:
  - name: framework
    description: The following frameworks are available - mocha, jasmine and qunit.
source_url: "https://github.com/NativeScript/nativescript-cli/blob/master/docs/man_pages/project/testing/test-init.md"
author: erodriguezh
author_url: "https://github.com/erodriguezh"
shells: []
