name: Configure NativeScript CLI usage reporting.
command: "ns usage-reporting"
tags:
  - nativescript
description: "Configures anonymous usage reporting for the NativeScript CLI."
source_url: "https://github.com/NativeScript/nativescript-cli/blob/master/docs/man_pages/general/usage-reporting.md"
author: erodriguezh
author_url: "https://github.com/erodriguezh"
shells: []
